# Generated by Django 5.0.2 on 2024-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0002_blogmodel_alter_usermodel_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='video',
            field=models.FileField(default=1, upload_to='media/'),
            preserve_default=False,
        ),
    ]
